---

- name: Install packages
  apt:
    name: nginx
    state: present
  become: true

- name: Install nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/oberon-server
  become: true

- name: Add log rotation
  template:
    src: logrotate/nginx
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644

- name: Enable site
  file:
    src: /etc/nginx/sites-available/oberon-server
    dest: /etc/nginx/sites-enabled/oberon-server
    state: link
  become: true

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Reload nginx configs
  shell: systemctl reload nginx
  become: true
