---

# Startup tasks

- name: Run database migrations
  shell: "{{ server_app_binary }} command release_manager migrate"
  ignore_errors: yes
  run_once: True

# Add service monitoring

- name: Add chat_server as a systemd service
  template:
    src: etc/systemd/system/chat_server.service.j2
    dest: /etc/systemd/system/chat_server.service
  become: yes

- name: Enable chat_server on restart
  shell: systemctl enable chat_server
  become: yes

- name: Reload systemctl daemon
  shell: systemctl daemon-reload
  become: yes

- name: Restart chat_server
  shell: systemctl restart chat_server
  become: yes
