#!/usr/bin/env python

import glob
import os
import re
from optparse import OptionParser


"""
Replaces placeholder create-react-app env values like:

    "PLACEHOLDER_REACT_APP_DOMAIN"

Is replaced with the `os.environ["REACT_APP_DOMAIN"]` value, becoming:

    "example.com"

Env variables are dynamically filtered by the pattern `REACT_APP_*`.
"""

def filtered_keys():
    keys = []
    for key in os.environ:
        if re.search(r'REACT_APP_.*', key):
            keys.append(key)
    return keys

def replace_placeholders(text):
    keys = filtered_keys()
    for key in keys:
        placeholder = "PLACEHOLDER_{}".format(key)
        replacement = os.environ[key]
        text = text.replace(placeholder, replacement)
    return text

def main():
    parser = OptionParser("Usage: %prog <file>")
    (options, args) = parser.parse_args()

    if len(args) < 1:
        parser.error("Incorrect number of arguments")

    for path in glob.glob(args[0]):
    	with open(path, "r+") as file:
            text = file.read()
    	    file.seek(0)
            result = replace_placeholders(text)
            file.write(result)
	    file.truncate()


if __name__ == "__main__":
    main()
